### ISSUE TITLE
output of solvers

### ISSUE THREAD

**Issue by oferst** [PatrickTrentin88/fzn2omt#8] opened 2020-06-04 20:30 UTC
The fzn files I am generating with mzn2fzn are full with thousands of declarations such as 
var bool: X_INTRODUCED_48_:: output_var;
(even if there is no OUTPUT statement in the mzn file, by the way). 
I assume that this is the reason that the output of e.g.  fzn2z3 gives value to all those internal variables. 
Is there a way to just see the output of the mzn decision variables ?
Thanks.

**Comment by PatrickTrentin88** [comment] 2020-06-04 22:23
> The fzn files I am generating with mzn2fzn are full with thousands of declarations such as
> var bool: X_INTRODUCED_48_:: output_var;

These are artificial variables introduced by the `mzn2fzn` compiler.

> (even if there is no OUTPUT statement in the mzn file, by the way).

That's the problem. Since there is no output statement in the `MiniZinc` model, all variables are promoted to output variables by the `mzn2fzn` compiler.

> I assume that this is the reason that the output of e.g. fzn2z3 gives value to all those internal variables.

Correct.

> Is there a way to just see the output of the mzn decision variables ?

Provide an output statement listing all and only the variables you are interested in.

> Thanks.

I am closing this issue because it is not caused by `fzn2omt` but by `mzn2fzn`.

**Closed as completed by PatrickTrentin88** 2020-06-04 22:23 UTC

**Comment by oferst** [comment] 2020-06-09 12:04
I rechecked the output issue. Even when the mzn file contains an output statement, the output of fzn2z3 contains all those auxiliary variables, and only a few of the variables that were in the original output statement. The formatted output itself (including labels) is not part of the output. I guess minizinc prints this formatted output based on the result from the solver. I am attaching a sample mzn (please rename the extension .txt to .mzn). See the output statement in lines 611-649.

Ofer

[note: edited because too long]

**Comment by PatrickTrentin88** [comment] 2020-06-09 22:19
@oferst Yeah, I guess I was wrong on this. In the future, I ought to test the information I am giving first or properly signal that I haven't. 

In any case, `fzn2z3.py` prints all and only those variables marked as output variables in the `FlatZinc` file by the `mzn2fzn` compiler. There is no way for me to fix this issue without violating the `FlatZinc` Specification.

---

_[I haven't personally tested what follows]_

What you may want to try to do is to configure the solvers distributed with `fzn2omt` as [MiniZinc backends](https://www.minizinc.org/doc-2.4.3/en/solvers.html).

**e.g.** On Linux, one would need to create the a configuration file similar to this and place it in `.minizinc/solvers`:

```
{
  "id": "optimathsat_int",
  "name": "OptiMathSAT (NIRA)",
  "description": "OptiMathSAT + OMT(NIRA)",
  "version": "1.7.0",
  "mznlib": "",
  "executable": "/opt/fzn2omt/bin/fzn2optimathsat.sh",
  "tags": ["cp","int"],
  "stdFlags": ["-a","-n","-p","-r","-f"],
  "supportsMzn": false,
  "supportsFzn": true,
  "needsSolns2Out": true,
  "needsMznExecutable": false,
  "needsStdlibDir": false,
  "isGUIApplication": false
 }
```

where `fzn2optimathsat.sh` is a **new** bash script that runs `fzn2optimathsat.py` with the correct options for the given configuration:

```
#!/bin/bash
python3 /.../fzn2omt/bin/fzn2optimathsat.py --finite-precision 20 --int-enc
```

Then it should be possible to run

```
minizinc --solver optimathsat_int model.mzn data.dzn
```

Since now `minizinc` is in control, I believe _(but I cannot guarantee)_ that the output should be properly formatted, similarly to what happens with other `FlatZinc` solvers.

Unfortunately, I haven't got the chance to test setting up the `fzn2omt` solvers as `MiniZinc` back-ends by myself. However, I know for a fact that someone else got it working. 

---

**IMPORTANT NOTE:** it appears to be necessary to create a new script `fzn2optimathsat.sh` to act as an intermediary for `fzn2optimathsat.py` because the `MiniZinc` solver does not appear to like solver options to be appended to the `executable` entry. (It doesn't have to be a `bash` script, it can be any executable without arguments).

**Comment by oferst** [comment] 2020-06-10 05:39
Thanks for the detailed answer!
Regarding the option of adding an smt solver into the pool of minizinc solvers:
Is there an option to hook fzn2z3 itself to minizinc ? this will enable solving with z3.

-- Ofer

**Comment by PatrickTrentin88** [comment] 2020-06-10 07:28
> Thanks for the detailed answer! Regarding the option of adding an smt solver into the pool of minizinc solvers: Is there an option to hook fzn2z3 itself to minizinc ? this will enable solving with z3.

Perhaps I was not clear in my previous message, but the idea is exactly that: add one configuration file for each `fzn2<whatever>.py` solver (or solver configuration), including `fzn2z3.py`.
